image: docker:19.03.1

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DOCKER_DRIVER: overlay2
  DATABASE_URL: "mongodb://mongo/user_posts"
  DOCKER_TLS_CERTDIR: ""

before_script:
  - cd reddit

build_job:
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - docker info
    - ../gitlab-ci/scripts/build-docker-image.sh

test_unit_job:
  image: ruby:2.4.2
  stage: test
  services:
    - mongo:latest
  script:
    - bundle install
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  services:
    - docker:19.03.1-dind
  stage: review
  script:
    - echo $CI_ENVIRONMENT_SLUG
    - docker run -d --hostname reddit --name gitlab-reddit-$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID --rm -p 9292:9292 evgeniyberendyaev/gitlab-reddit:$CI_PIPELINE_IID
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
