---
dependencies:
  - name: ui
    version: "2.0.0"
    repository: "file://../ui"

  - name: post
    version: "2.0.0"
    repository: "file://../post"

  - name: comment
    version: "2.0.0"
    repository: "file://../comment"

  - name: mongodb
    version: 7.2.8
    repository: https://kubernetes-charts.storage.googleapis.com
