global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '@alertmanager'
