version: "3.3"
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:${DB_VOL_PATH}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui
    ports:
      - target: ${FE_CONTAINER_PORT}
        published: ${FE_HOST_PORT}
        protocol: ${PROTO}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - ${FRONTEND_NW}

  post:
    image: ${USERNAME}/post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - ${FRONTEND_NW}
      - ${BACKEND_NW}

  comment:
    image: ${USERNAME}/comment
    container_name: comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - ${FRONTEND_NW}
      - ${BACKEND_NW}

volumes:
  post_db:

networks:
  front_net:
  back_net:
