version: "3.3"
services:
  prometheus:
    build: ../monitoring/prometheus
    image: ${USERNAME}/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=1d"
    networks:
      - ${FRONTEND_NW}
      - ${BACKEND_NW}
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - ${FRONTEND_NW}
      - ${BACKEND_NW}
  mongo-exporter:
    image: ${USERNAME}/mongodb_exporter
    command: --mongodb.uri mongodb://post_db:27017
    networks:
      - ${BACKEND_NW}
  blackbox-exporter:
    build: ../monitoring/blackbox_exporter
    image: ${USERNAME}/blackbox_exporter
    networks:
      - ${FRONTEND_NW}
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "8080:8080"
    networks:
      - ${FRONTEND_NW}
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - ${FRONTEND_NW}
  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
    ports:
      - 9093:9093
    networks:
      - ${FRONTEND_NW}

volumes:
  prometheus_data:
  grafana_data:

networks:
  front_net:
  back_net:
